// Generated by CoffeeScript 1.10.0
var COMPILE, EXTRACT, HELP, commandDefinition, parseArgs, parseCommand, parsedArgs, parsedCommand;

parseArgs = require('minimist');

parseCommand = require('minimist-subcommand');

HELP = 'help';

EXTRACT = 'extract';

COMPILE = 'compile';

commandDefinition = {
  "default": HELP,
  commands: {}
};

commandDefinition.commands[HELP] = null;

commandDefinition.commands[EXTRACT] = null;

commandDefinition.commands[COMPILE] = null;

parsedCommand = parseCommand(commandDefinition, process.argv.slice(2));

parsedArgs = parseArgs(parsedCommand.argv);

module.exports = {
  HELP: HELP,
  EXTRACT: EXTRACT,
  COMPILE: COMPILE,
  subcommand: parsedCommand.commands[0],
  args: parsedArgs
};
