// Generated by CoffeeScript 1.10.0
var Compiler, Extractor, app, option, usage;

option = require('./argparser.js');

usage = require('./help.js');

Extractor = require('./extract.js');

Compiler = require('./compile.js');

app = {};

app[option.HELP] = function() {
  return usage();
};

app[option.EXTRACT] = function() {
  var extractor;
  console.log('Running extract phase', this._args);
  extractor = new Extractor(this._args);
  return extractor.run();
};

app[option.COMPILE] = function() {
  var compiler;
  console.log('Running compile phase', this._args);
  compiler = new Compiler(this._args);
  return compiler.run();
};

app['_args'] = option.args;

app['_handler'] = app[option.subcommand];

app['run'] = function() {
  return this._handler();
};

module.exports = app;
