// Generated by CoffeeScript 1.10.0
var CliCompiler, Compiler, fs, glob;

fs = require('fs');

glob = require('glob');

Compiler = require('angular-gettext-tools').Compiler;

CliCompiler = (function() {
  function CliCompiler(argv) {
    this._initArgs(argv);
    this.compiler = new Compiler({
      format: 'javascript',
      module: 'gettext'
    });
  }

  CliCompiler.prototype._initArgs = function(argv) {
    if (!argv.output) {
      throw new Error('output parameter missing');
    }
    this.output = argv.output;
    return this.files = argv._;
  };

  CliCompiler.prototype.run = function() {
    var allContent, content, fileGlob, fileName, i, j, len, len1, ref, ref1;
    console.log('Started compiling...');
    allContent = [];
    ref = this.files;
    for (i = 0, len = ref.length; i < len; i++) {
      fileGlob = ref[i];
      ref1 = glob.sync(fileGlob);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        fileName = ref1[j];
        console.log('- ', fileName);
        content = fs.readFileSync(fileName, 'utf8');
        allContent.push(content);
      }
    }
    console.log('Finished reading sources');
    fs.writeFileSync(this.output, this.compiler.convertPo(allContent).toString(), null, function(error) {
      if (err) {
        throw err;
      }
    });
    return console.log('Saved to file', this.output);
  };

  return CliCompiler;

})();

module.exports = CliCompiler;
