// Generated by CoffeeScript 1.10.0
var CliExtractor, Extractor, fs, glob;

fs = require('fs');

glob = require('glob');

Extractor = require('angular-gettext-tools').Extractor;

CliExtractor = (function() {
  function CliExtractor(argv) {
    this._initArgs(argv);
    this.extractor = new Extractor({
      markerName: argv['marker-name']
    });
  }

  CliExtractor.prototype._initArgs = function(argv) {
    if (!argv.output) {
      throw new Error('dest parameter missing');
    }
    this.output = argv.output;
    return this.files = argv._;
  };

  CliExtractor.prototype.run = function() {
    var content, fileGlob, fileName, i, j, len, len1, ref, ref1;
    console.log('Started parsing...');
    ref = this.files;
    for (i = 0, len = ref.length; i < len; i++) {
      fileGlob = ref[i];
      ref1 = glob.sync(fileGlob);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        fileName = ref1[j];
        console.log('- ', fileName);
        content = fs.readFileSync(fileName, 'utf8');
        this.extractor.parse(fileName, content);
      }
    }
    console.log('Finished parsing');
    fs.writeFileSync(this.output, this.extractor.toString(), null, function(error) {
      if (err) {
        throw err;
      }
    });
    return console.log('Saved to file', this.output);
  };

  return CliExtractor;

})();

module.exports = CliExtractor;
